name: Await Remote Workflow
description: 'Triggers a remote workflow and waits for it to complete'
inputs:
  workflow-org:
    description: 'the worklflow"s organization/username on Github'
    required: false
    default: 'anecdotes-ai'
  workflow-repo:
    description: 'the workflow"s Github repository/project name'
    required: true
  workflow-yaml:
    description: 'the workflow"s yaml action file name'
    required: true
  workflow-branch:
    description: 'the branch from which the triggered workflow would be executed'
    required: true
  workflow-inputs:
    description: 'additional space-delimited workflow inputs in the var=value format'
    required: false
    default: 'none'
  github-auth-token:
    description: 'the Github authentication token to use for POST/GET requests on Github'
    required: true
  wait-timeout-in-minutes:
    description: 'how long we wait for the triggered workflow to complete'
    required: 'false'
    default: '10'
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/await-remote-workflow.sh \
        --workflow-org ${{ inputs.workflow-org }} \
        --workflow-repo ${{ inputs.workflow-repo }} \
        --workflow-yaml ${{ inputs.workflow-yaml }} \
        --workflow-branch ${{ inputs.workflow-branch }} \
        --auth-token ${{ inputs.github-auth-token }} \
        --wait-timeout-minutes ${{ inputs.wait-timeout-in-minutes }} \
        --workflow-inputs "${{ inputs.workflow-inputs }}"
      shell: bash
